### ISSUE TITLE
Untrusted Application Install

### ISSUE THREAD

**Issue by jelliuk** [beeradmoore/dlss_version_tracker#1]
When attempting to install the MSIX the default Windows 10 Security Permissions will prevent this given the utilised certificate is not able to be trusted - [Details Here](https://docs.microsoft.com/en-us/windows/msix/app-installer/troubleshoot-appinstaller-issues)

To allow me to install I had to perform the following steps:

**Enable Developer Mode**
1. Settings
2. Update & Security
3. For Developers
4. Use Developer features : Developer Mode

**Install the Certificate** 
1. Right click on APPX file
2. Click Properties
3. Click Digital Signatures
4. Select Signature from the list
5. Click Details
6. Click View Certificate
7. Click Install Certificate
8. Store location = Local machine
9. Place all certificates in the following store = Third-Party Root Certification Authorities

I'd advise this be added to the readme or alternatively utilisation of a trusted certificate authority would be much more beneficial and user friendly.

**Comment by beeradmoore** [comment]
(FYI, wrong repo, I think you meant to put this on DLSS Swapper)

Did you follow the install instructions or just download the release bundle and run that?

I re-tested on my spare PC and it also worked with the cert installed into 3rd party root instead of root (which is preferred IMO, I'll see if I can even bring it down more)

But I didn't need to install developer mode. This is on a PC running Win10 21H1 with no dev tools installed.

**Comment by beeradmoore** [comment]
Was able to confirm I could reduce the cert store way down to "Trusted People" which is 100000x better than throwing it in the root cert store. Thank you for bringing that to my attention.

**Comment by jelliuk** [comment]
Apologies, yes I had too many Github windows open and mistakenly posted this into the wrong repo.  Sorry about that.  

I was fairly certain there would be a more appropriate Cert to go with, I just did a few google searches and that was one of the options.  Thanks for fine tuning it as you're right, it's definitely better to get it more fine grained than the catch all above.

**Comment by beeradmoore** [comment]
If you have any other problems or questions (or big security holes that I shouldn't be doing lol) again please feel free to file more issues or contact me directly on Twitter.
